
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OP_DECSEC = 6;
  public static final int OP_ENDECSEC = 7;
  public static final int OP_BETWEEN = 10;
  public static final int OP_INT = 11;
  public static final int MAY_EQ = 31;
  public static final int OP_WHILE = 2;
  public static final int OP_ELSE = 4;
  public static final int OP_FLOAT = 12;
  public static final int MINUS = 28;
  public static final int OP_DIV = 17;
  public static final int AND = 35;
  public static final int NOT = 34;
  public static final int CTE_BIN = 41;
  public static final int OP_ENDPROSEC = 9;
  public static final int OR = 36;
  public static final int OP_MUL = 16;
  public static final int ID = 37;
  public static final int DECLA = 19;
  public static final int EOF = 0;
  public static final int PAR_CL = 21;
  public static final int error = 1;
  public static final int PAR_OP = 20;
  public static final int COMA = 27;
  public static final int OP_PROSEC = 8;
  public static final int DOTCOM = 26;
  public static final int NEQ = 33;
  public static final int BRA_CL = 25;
  public static final int EQ = 32;
  public static final int OP_IF = 3;
  public static final int BRA_OP = 24;
  public static final int SQR_CL = 23;
  public static final int OP_WRITE = 5;
  public static final int SQR_OP = 22;
  public static final int OP_SUM = 14;
  public static final int OP_LESS = 15;
  public static final int CTE_STR = 40;
  public static final int CTE_REAL = 39;
  public static final int CTE_INT = 38;
  public static final int ASIGN = 18;
  public static final int MINUS_EQ = 29;
  public static final int MAY = 30;
  public static final int OP_STRING = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "OP_WHILE",
  "OP_IF",
  "OP_ELSE",
  "OP_WRITE",
  "OP_DECSEC",
  "OP_ENDECSEC",
  "OP_PROSEC",
  "OP_ENDPROSEC",
  "OP_BETWEEN",
  "OP_INT",
  "OP_FLOAT",
  "OP_STRING",
  "OP_SUM",
  "OP_LESS",
  "OP_MUL",
  "OP_DIV",
  "ASIGN",
  "DECLA",
  "PAR_OP",
  "PAR_CL",
  "SQR_OP",
  "SQR_CL",
  "BRA_OP",
  "BRA_CL",
  "DOTCOM",
  "COMA",
  "MINUS",
  "MINUS_EQ",
  "MAY",
  "MAY_EQ",
  "EQ",
  "NEQ",
  "NOT",
  "AND",
  "OR",
  "ID",
  "CTE_INT",
  "CTE_REAL",
  "CTE_STR",
  "CTE_BIN"
  };
}

